#车辆登入时间越界:
"1": null
#车辆登入流水号越界:
"3": null
#电池管理系统数越界:
"5": null
#电池管理系统对应动力蓄电池包个数越界:
"6": null
#车辆数据采集时间越界:
"9": null
#车辆登出时间越界:
"11": null
#车辆登出流水号越界:
"13": null
#平台登入时间越界:
"15": null
#平台登入流水号越界:
"17": null
#平台登出时间越界:
"18": null
#平台登出流水号越界:
"20": null
#车辆状态异常:车辆状态
"22": "220C"
#车辆状态无效:车辆状态
"23": "220C"
#车辆状态无定义:车辆状态
"24": "220C"
#充电状态异常:充电状态
"25": "21AA"
#充电状态无效:充电状态
"26": "21AA"
#充电状态无定义:充电状态
"27": "21AA"
#运行模式异常:运行模式
"28": "21AB"
#运行模式无效:运行模式
"29": "21AB"
#运行模式无定义:运行模式
"30": "21AB"
#车速异常:车速
"31": "2001"
#车速无效:车速
"32": "2001"
#车速越界:车速
"33": "2001"
#累计里程异常:公里里程（总里程）
"34": "2009"
#累计里程无效:公里里程（总里程）
"35": "2009"
#累计里程越界:公里里程（总里程）
"36": "2009"
#总电压异常:总电压
"37": "215C"
#总电压无效:总电压
"38": "215C"
#总电压越界:总电压
"39": "215C"
#总电流异常:总电流
"40": "215D"
#总电流无效:总电流
"41": "215D"
#总电流越界:总电流
"42": "215D"
#SOC 异常:soc
"43": "2232"
#SOC 无效:soc
"44": "2232"
#SOC 越界:soc
"45": "2232"
#DC-DC 状态异常:DC-DC状态
"46": "2187"
#DC-DC 状态无效:DC-DC状态
"47": "2187"
#DC-DC 状态无定义:DC-DC状态
"48": "2187"
#档位状态位未定义:
"49": null
#高压对地绝缘电阻越界:
"50": null
#动力蓄电池包个数异常:
"51": null
#动力蓄电池包个数无效:
"52": null
#动力蓄电池包个数越界:
"53": null
#动力蓄电池包号异常:
"55": null
#动力蓄电池包号无效:
"56": null
#动力蓄电池包号越界:
"57": null
#动力蓄电池包电压异常:
"58": null
#动力蓄电池包电压无效:
"59": null
#动力蓄电池包电压越界:
"60": null
#动力蓄电池包电流异常:
"61": null
#动力蓄电池包电流无效:
"62": null
#动力蓄电池包电流越界:
"63": null
#最小并联单元总数异常:
"64": null
#最小并联单元总数无效:
"65": null
#最小并联单元总数越界:
"66": null
#本帧最小并联单元电压异常:
"67": null
#本帧最小并联单元电压无效:
"68": null
#本帧最小并联单元电压越界:
"69": null
#动力蓄电池包温度探针个数异常:
"71": null
#动力蓄电池包温度探针个数无效:
"72": null
#动力蓄电池包温度探针个数越界:
"73": null
#温度探针检测到的温度值异常:
"74": null
#温度探针检测到的温度值无效:
"75": null
#温度探针检测到的温度值越界:
"76": null
#驱动电机个数越界:
"77": null
#驱动电机序号越界:
"79": null
#驱动电机状态异常:
"80": null
#驱动电机状态无效:
"81": null
#驱动电机状态无定义:
"82": null
#驱动电机控制器温度异常:
"83": null
#驱动电机控制器温度无效:
"84": null
#驱动电机控制器温度越界:
"85": null
#驱动电机转速异常:
"86": null
#驱动电机转速无效:
"87": null
#驱动电机转速越界:
"88": null
#驱动电机转矩异常:
"89": null
#驱动电机转矩无效:
"90": null
#驱动电机转矩越界:
"91": null
#驱动电机温度异常:
"92": null
#驱动电机温度无效:
"93": null
#驱动电机温度越界:
"94": null
#车载氢系统中最高温度异常:
"95": null
#车载氢系统中最高温度无效:
"96": null
#车载氢系统中最高温度越界:
"97": null
#车载氢系统中最高温度探针代号异常:
"98": null
#车载氢系统中最高温度探针代号无效:
"99": null
#车载氢系统中最高温度探针代号越界:
"100": null
#氢气最高浓度异常:
"101": null
#氢气最高浓度无效:
"102": null
#氢气最高浓度越界:
"103": null
#氢气最高浓度传感器代号异常:
"104": null
#氢气最高浓度传感器代号无效:
"105": null
#氢气最高浓度传感器代号越界:
"106": null
#氢气最高压力异常:
"107": null
#氢气最高压力无效:
"108": null
#氢气最高压力越界:
"109": null
#氢气最高压力传感器代号异常:
"110": null
#氢气最高压力传感器代号无效:
"111": null
#氢气最高压力传感器代号越界:
"112": null
#高压 DC/DC 状态异常:
"113": null
#高压 DC/DC 状态无效:
"114": null
#高压 DC/DC 状态无定义:
"115": null
#剩余氢量百分比异常:
"116": null
#剩余氢量百分比无效:
"117": null
#剩余氢量百分比越界:
"118": null
#高压 DC/DC 控制器温度异常:
"119": null
#高压 DC/DC 控制器温度无效:
"120": null
#高压 DC/DC 控制器温度越界:
"121": null
#燃料电池电堆个数异常:
"122": null
#燃料电池电堆个数无效:
"123": null
#燃料电池电堆个数越界:
"124": null
#燃料电池电堆序号异常:
"126": null
#燃料电池电堆序号无效:
"127": null
#燃料电池电堆序号越界:
"128": null
#燃料电池电堆电压异常:
"129": null
#燃料电池电堆电压无效:
"130": null
#燃料电池电堆电压越界:
"131": null
#燃料电池电堆电流异常:
"132": null
#燃料电池电堆电流无效:
"133": null
#燃料电池电堆电流越界:
"134": null
#氢气入口压力异常:
"135": null
#氢气入口压力无效:
"136": null
#氢气入口压力越界:
"137": null
#空气入口压力异常:
"138": null
#空气入口压力无效:
"139": null
#空气入口压力越界:
"140": null
#空气入口温度异常:
"141": null
#空气入口温度无效:
"142": null
#空气入口温度越界:
"143": null
#冷却水出水口温度探针总数异常:
"144": null
#冷却水出水口温度探针总数无效:
"145": null
#冷却水出水口温度探针总数越界:
"146": null
#冷却水出水口温度越界:
"147": null
#曲轴转速异常:曲轴转速
"148": "219F"
#曲轴转速无效:曲轴转速
"149": "219F"
#曲轴转速越界:曲轴转速
"150": "219F"
#定位状态未定义:
"151": null
#经度越界:经度
"154": "207A"
#纬度越界:纬度
"155": "207B"
#最高报警等级异常:最高报警等级
"159": "220B"
#最高报警等级无效:最高报警等级
"160": "220B"
#最高报警等级无定义:最高报警等级
"161": "220B"
#可充电储能装置故障总数 N1异常:
"164": null
#可充电储能装置故障总数 N1无效:
"165": null
#可充电储能装置故障总数 N1越界:
"166": null
#驱动电机故障总数 N2 异常:
"168": null
#驱动电机故障总数 N2 无效:
"169": null
#驱动电机故障总数 N2 越界:
"170": null
#发动机故障总数 N3 异常:
"172": null
#发动机故障总数 N3 无效:
"173": null
#发动机故障总数 N3 越界:
"174": null
#其他故障总数 N4 异常:
"176": null
#其他故障总数 N4 无效:
"177": null
#其他故障总数 N4 越界:
"178": null
#通用报警故障总数异常:
"180": null
#通用报警故障总数无效:
"181": null
#通用报警故障总数越界:
"182": null
#超级电容管理系统号异常:
"184": null
#超级电容管理系统号无效:
"185": null
#超级电容管理系统号越界:
"186": null
#超级电容总电压异常:
"187": null
#超级电容总电压无效:
"188": null
#超级电容总电压越界:
"189": null
#超级电容总电流异常:
"190": null
#超级电容总电流无效:
"191": null
#超级电容总电流越界:
"192": null
#超级电容单体总数异常:
"193": null
#超级电容单体总数无效:
"194": null
#超级电容单体总数越界:
"195": null
#超级电容单体电压异常:
"197": null
#超级电容单体电压无效:
"198": null
#超级电容单体电压越界:
"199": null
#超级电容温度探针总数异常:
"200": null
#超级电容温度探针总数无效:
"201": null
#超级电容温度探针总数越界:
"202": null
#探针温度值异常:
"204": null
#探针温度值无效:
"205": null
#探针温度值越界:
"206": null
#最高电压管理系统号异常:
"207": null
#最高电压管理系统号无效:
"208": null
#最高电压管理系统号越界:
"209": null
#最高电压超级电容单体代号越界:
"210": null
#超级电容单体电压最高值异常:
"211": null
#超级电容单体电压最高值无效:
"212": null
#超级电容单体电压最高值越界:
"213": null
#最低电压管理系统号异常:
"215": null
#最低电压管理系统号无效:
"216": null
#最低电压管理系统号越界:
"217": null
#最低电压超级电容单体代号越界:
"218": null
#超级电容单体电压最低值异常:
"219": null
#超级电容单体电压最低值无效:
"220": null
#超级电容单体电压最低值越界:
"221": null
#最高温度管理系统号异常:
"223": null
#最高温度管理系统号无效:
"224": null
#最高温度管理系统号越界:
"225": null
#最高温度探针代号越界:
"226": null
#最高温度值异常:最高温度值
"227": "2143"
#最高温度值无效:最高温度值
"228": "2143"
#最高温度值越界:最高温度值
"229": "2143"
#最低温度管理系统号异常:
"231": null
#最低温度管理系统号无效:
"232": null
#最低温度管理系统号越界:
"233": null
#最低温度探针代号越界:
"234": null
#最低温度值异常:最低温度值
"235": "2145"
#最低温度值无效:最低温度值
"236": "2145"
#最低温度值越界:最低温度值
"237": "2145"
#未上传整车数据:
"239": null
#未上传动力蓄电池最小并联单元电压数据:
"240": null
#未上传动力蓄电池温度数据:
"241": null
#未上传驱动电机数据:
"242": null
#未上传燃料电池发动机及车载氢系统数据:
"243": null
#未上传燃料电池电堆数据:
"244": null
#未上传发动机数据:
"245": null
#未上传车辆位置数据:
"246": null
#未上传超级电容器数据:
"247": null
#未上传超级电容器极值数据:
"248": null
#坐标系异常:
"251": null
#坐标系无效:
"252": null
#坐标系无定义:
"253": null
#未上传报警数据:
"258": null
#车辆状态非 1 启动且非 2 熄火:
"259": null