#车辆登入时间越界:车辆登入时间
"1": "车辆登入时间"
#车辆登入流水号越界:车辆登入流水号
"3": "车辆登入流水号"
#电池管理系统数越界:电池管理系统数
"5": "电池管理系统数"
#电池管理系统对应动力蓄电池包个数越界:电池管理系统对应动力蓄电池包个数
"6": "电池管理系统对应动力蓄电池包个数"
#车辆数据采集时间越界:车辆数据采集时间
"9": "车辆数据采集时间"
#车辆登出时间越界:车辆登出时间
"11": "车辆登出时间"
#车辆登出流水号越界:车辆登出流水号
"13": "车辆登出流水号"
#平台登入时间越界:平台登入时间
"15": "平台登入时间"
#平台登入流水号越界:平台登入流水号
"17": "平台登入流水号"
#平台登出时间越界:平台登出时间
"18": "平台登出时间"
#平台登出流水号越界:平台登出流水号
"20": "平台登出流水号"
#车辆状态异常:车辆状态
"22": "220C"
#车辆状态无效:车辆状态
"23": "220C"
#车辆状态无定义:车辆状态
"24": "220C"
#充电状态异常:充电状态
"25": "21AA"
#充电状态无效:充电状态
"26": "21AA"
#充电状态无定义:充电状态
"27": "21AA"
#运行模式异常:运行模式
"28": "21AB"
#运行模式无效:运行模式
"29": "21AB"
#运行模式无定义:运行模式
"30": "21AB"
#车速异常:车速
"31": "2001"
#车速无效:车速
"32": "2001"
#车速越界:车速
"33": "2001"
#累计里程异常:公里里程（总里程）
"34": "2009"
#累计里程无效:公里里程（总里程）
"35": "2009"
#累计里程越界:公里里程（总里程）
"36": "2009"
#总电压异常:总电压
"37": "215C"
#总电压无效:总电压
"38": "215C"
#总电压越界:总电压
"39": "215C"
#总电流异常:总电流
"40": "215D"
#总电流无效:总电流
"41": "215D"
#总电流越界:总电流
"42": "215D"
#SOC 异常:soc
"43": "2232"
#SOC 无效:soc
"44": "2232"
#SOC 越界:soc
"45": "2232"
#DC-DC 状态异常:DC-DC状态
"46": "2187"
#DC-DC 状态无效:DC-DC状态
"47": "2187"
#DC-DC 状态无定义:DC-DC状态
"48": "2187"
#档位状态位未定义:档位
"49": "2076"
#高压对地绝缘电阻越界:高压对地绝缘电阻
"50": "高压对地绝缘电阻"
#动力蓄电池包个数异常:动力蓄电池包个数
"51": "动力蓄电池包个数"
#动力蓄电池包个数无效:动力蓄电池包个数
"52": "动力蓄电池包个数"
#动力蓄电池包个数越界:动力蓄电池包个数
"53": "动力蓄电池包个数"
#动力蓄电池包号异常:动力蓄电池包号
"55": "动力蓄电池包号"
#动力蓄电池包号无效:动力蓄电池包号
"56": "动力蓄电池包号"
#动力蓄电池包号越界:动力蓄电池包号
"57": "动力蓄电池包号"
#动力蓄电池包电压异常:动力蓄电池包电压
"58": "动力蓄电池包电压"
#动力蓄电池包电压无效:动力蓄电池包电压
"59": "动力蓄电池包电压"
#动力蓄电池包电压越界:动力蓄电池包电压
"60": "动力蓄电池包电压"
#动力蓄电池包电流异常:动力蓄电池包电流
"61": "动力蓄电池包电流"
#动力蓄电池包电流无效:动力蓄电池包电流
"62": "动力蓄电池包电流"
#动力蓄电池包电流越界:动力蓄电池包电流
"63": "动力蓄电池包电流"
#最小并联单元总数异常:最小并联单元总数
"64": "最小并联单元总数"
#最小并联单元总数无效:最小并联单元总数
"65": "最小并联单元总数"
#最小并联单元总数越界:最小并联单元总数
"66": "最小并联单元总数"
#本帧最小并联单元电压异常:本帧最小并联单元电压
"67": "本帧最小并联单元电压"
#本帧最小并联单元电压无效:本帧最小并联单元电压
"68": "本帧最小并联单元电压"
#本帧最小并联单元电压越界:本帧最小并联单元电压
"69": "本帧最小并联单元电压"
#动力蓄电池包温度探针个数异常:动力蓄电池包温度探针个数
"71": "动力蓄电池包温度探针个数"
#动力蓄电池包温度探针个数无效:动力蓄电池包温度探针个数
"72": "动力蓄电池包温度探针个数"
#动力蓄电池包温度探针个数越界:动力蓄电池包温度探针个数
"73": "动力蓄电池包温度探针个数"
#温度探针检测到的温度值异常:温度探针检测到的温度值
"74": "温度探针检测到的温度值"
#温度探针检测到的温度值无效:温度探针检测到的温度值
"75": "温度探针检测到的温度值"
#温度探针检测到的温度值越界:温度探针检测到的温度值
"76": "温度探针检测到的温度值"
#驱动电机个数越界:驱动电机个数
"77": "驱动电机个数"
#驱动电机序号越界:驱动电机序号
"79": "驱动电机序号"
#驱动电机状态异常:驱动电机状态
"80": "驱动电机状态"
#驱动电机状态无效:驱动电机状态
"81": "驱动电机状态"
#驱动电机状态无定义:驱动电机状态
"82": "驱动电机状态"
#驱动电机控制器温度异常:驱动电机控制器温度
"83": "驱动电机控制器温度"
#驱动电机控制器温度无效:驱动电机控制器温度
"84": "驱动电机控制器温度"
#驱动电机控制器温度越界:驱动电机控制器温度
"85": "驱动电机控制器温度"
#驱动电机转速异常:驱动电机转速
"86": "驱动电机转速"
#驱动电机转速无效:驱动电机转速
"87": "驱动电机转速"
#驱动电机转速越界:驱动电机转速
"88": "驱动电机转速"
#驱动电机转矩异常:驱动电机转矩
"89": "驱动电机转矩"
#驱动电机转矩无效:驱动电机转矩
"90": "驱动电机转矩"
#驱动电机转矩越界:驱动电机转矩
"91": "驱动电机转矩"
#驱动电机温度异常:驱动电机温度
"92": "驱动电机温度"
#驱动电机温度无效:驱动电机温度
"93": "驱动电机温度"
#驱动电机温度越界:驱动电机温度
"94": "驱动电机温度"
#车载氢系统中最高温度异常:车载氢系统中最高温度
"95": "车载氢系统中最高温度"
#车载氢系统中最高温度无效:车载氢系统中最高温度
"96": "车载氢系统中最高温度"
#车载氢系统中最高温度越界:车载氢系统中最高温度
"97": "车载氢系统中最高温度"
#车载氢系统中最高温度探针代号异常:车载氢系统中最高温度探针代号
"98": "车载氢系统中最高温度探针代号"
#车载氢系统中最高温度探针代号无效:车载氢系统中最高温度探针代号
"99": "车载氢系统中最高温度探针代号"
#车载氢系统中最高温度探针代号越界:车载氢系统中最高温度探针代号
"100": "车载氢系统中最高温度探针代号"
#氢气最高浓度异常:氢气最高浓度
"101": "氢气最高浓度"
#氢气最高浓度无效:氢气最高浓度
"102": "氢气最高浓度"
#氢气最高浓度越界:氢气最高浓度
"103": "氢气最高浓度"
#氢气最高浓度传感器代号异常:氢气最高浓度传感器代号
"104": "氢气最高浓度传感器代号"
#氢气最高浓度传感器代号无效:氢气最高浓度传感器代号
"105": "氢气最高浓度传感器代号"
#氢气最高浓度传感器代号越界:氢气最高浓度传感器代号
"106": "氢气最高浓度传感器代号"
#氢气最高压力异常:氢气最高压力
"107": "氢气最高压力"
#氢气最高压力无效:氢气最高压力
"108": "氢气最高压力"
#氢气最高压力越界:氢气最高压力
"109": "氢气最高压力"
#氢气最高压力传感器代号异常:氢气最高压力传感器代号
"110": "氢气最高压力传感器代号"
#氢气最高压力传感器代号无效:氢气最高压力传感器代号
"111": "氢气最高压力传感器代号"
#氢气最高压力传感器代号越界:氢气最高压力传感器代号
"112": "氢气最高压力传感器代号"
#高压 DC/DC 状态异常:
"113": "高压DC_DC状态"
#高压 DC/DC 状态无效:
"114": "高压DC_DC状态"
#高压 DC/DC 状态无定义:
"115": "高压DC_DC状态"
#剩余氢量百分比异常:剩余氢量百分比
"116": "剩余氢量百分比"
#剩余氢量百分比无效:剩余氢量百分比
"117": "剩余氢量百分比"
#剩余氢量百分比越界:剩余氢量百分比
"118": "剩余氢量百分比"
#高压 DC/DC 控制器温度异常:
"119": "高压DC_DC控制器温度"
#高压 DC/DC 控制器温度无效:
"120": "高压DC_DC控制器温度"
#高压 DC/DC 控制器温度越界:
"121": "高压DC_DC控制器温度"
#燃料电池电堆个数异常:燃料电池电堆个数
"122": "燃料电池电堆个数"
#燃料电池电堆个数无效:燃料电池电堆个数
"123": "燃料电池电堆个数"
#燃料电池电堆个数越界:燃料电池电堆个数
"124": "燃料电池电堆个数"
#燃料电池电堆序号异常:燃料电池电堆序号
"126": "燃料电池电堆序号"
#燃料电池电堆序号无效:燃料电池电堆序号
"127": "燃料电池电堆序号"
#燃料电池电堆序号越界:燃料电池电堆序号
"128": "燃料电池电堆序号"
#燃料电池电堆电压异常:燃料电池电堆电压
"129": "燃料电池电堆电压"
#燃料电池电堆电压无效:燃料电池电堆电压
"130": "燃料电池电堆电压"
#燃料电池电堆电压越界:燃料电池电堆电压
"131": "燃料电池电堆电压"
#燃料电池电堆电流异常:燃料电池电堆电流
"132": "燃料电池电堆电流"
#燃料电池电堆电流无效:燃料电池电堆电流
"133": "燃料电池电堆电流"
#燃料电池电堆电流越界:燃料电池电堆电流
"134": "燃料电池电堆电流"
#氢气入口压力异常:氢气入口压力
"135": "氢气入口压力"
#氢气入口压力无效:氢气入口压力
"136": "氢气入口压力"
#氢气入口压力越界:氢气入口压力
"137": "氢气入口压力"
#空气入口压力异常:空气入口压力
"138": "空气入口压力"
#空气入口压力无效:空气入口压力
"139": "空气入口压力"
#空气入口压力越界:空气入口压力
"140": "空气入口压力"
#空气入口温度异常:空气入口温度
"141": "空气入口温度"
#空气入口温度无效:空气入口温度
"142": "空气入口温度"
#空气入口温度越界:空气入口温度
"143": "空气入口温度"
#冷却水出水口温度探针总数异常:冷却水出水口温度探针总数
"144": "冷却水出水口温度探针总数"
#冷却水出水口温度探针总数无效:冷却水出水口温度探针总数
"145": "冷却水出水口温度探针总数"
#冷却水出水口温度探针总数越界:冷却水出水口温度探针总数
"146": "冷却水出水口温度探针总数"
#冷却水出水口温度越界:冷却水出水口温度
"147": "冷却水出水口温度"
#曲轴转速异常:曲轴转速
"148": "219F"
#曲轴转速无效:曲轴转速
"149": "219F"
#曲轴转速越界:曲轴转速
"150": "219F"
#定位状态未定义:定位状态未定义
"151": "定位状态未定义"
#经度越界:经度
"154": "207A"
#纬度越界:纬度
"155": "207B"
#最高报警等级异常:最高报警等级
"159": "220B"
#最高报警等级无效:最高报警等级
"160": "220B"
#最高报警等级无定义:最高报警等级
"161": "220B"
#可充电储能装置故障总数 N1异常:
"164": "可充电储能装置故障总数N1"
#可充电储能装置故障总数 N1无效:
"165": "可充电储能装置故障总数N1"
#可充电储能装置故障总数 N1越界:
"166": "可充电储能装置故障总数N1"
#驱动电机故障总数 N2 异常:
"168": "驱动电机故障总数N2"
#驱动电机故障总数 N2 无效:
"169": "驱动电机故障总数N2"
#驱动电机故障总数 N2 越界:
"170": "驱动电机故障总数N2"
#发动机故障总数 N3 异常:
"172": "发动机故障总数N3"
#发动机故障总数 N3 无效:
"173": "发动机故障总数N3"
#发动机故障总数 N3 越界:
"174": "发动机故障总数N3"
#其他故障总数 N4 异常:
"176": "其他故障总数N4"
#其他故障总数 N4 无效:
"177": "其他故障总数N4"
#其他故障总数 N4 越界:
"178": "其他故障总数N4"
#通用报警故障总数异常:通用报警故障总数
"180": "通用报警故障总数"
#通用报警故障总数无效:通用报警故障总数
"181": "通用报警故障总数"
#通用报警故障总数越界:通用报警故障总数
"182": "通用报警故障总数"
#超级电容管理系统号异常:超级电容管理系统号
"184": "超级电容管理系统号"
#超级电容管理系统号无效:超级电容管理系统号
"185": "超级电容管理系统号"
#超级电容管理系统号越界:超级电容管理系统号
"186": "超级电容管理系统号"
#超级电容总电压异常:超级电容总电压
"187": "超级电容总电压"
#超级电容总电压无效:超级电容总电压
"188": "超级电容总电压"
#超级电容总电压越界:超级电容总电压
"189": "超级电容总电压"
#超级电容总电流异常:超级电容总电流
"190": "超级电容总电流"
#超级电容总电流无效:超级电容总电流
"191": "超级电容总电流"
#超级电容总电流越界:超级电容总电流
"192": "超级电容总电流"
#超级电容单体总数异常:超级电容单体总数
"193": "超级电容单体总数"
#超级电容单体总数无效:超级电容单体总数
"194": "超级电容单体总数"
#超级电容单体总数越界:超级电容单体总数
"195": "超级电容单体总数"
#超级电容单体电压异常:超级电容单体电压
"197": "超级电容单体电压"
#超级电容单体电压无效:超级电容单体电压
"198": "超级电容单体电压"
#超级电容单体电压越界:超级电容单体电压
"199": "超级电容单体电压"
#超级电容温度探针总数异常:超级电容温度探针总数
"200": "超级电容温度探针总数"
#超级电容温度探针总数无效:超级电容温度探针总数
"201": "超级电容温度探针总数"
#超级电容温度探针总数越界:超级电容温度探针总数
"202": "超级电容温度探针总数"
#探针温度值异常:探针温度值
"204": "探针温度值"
#探针温度值无效:探针温度值
"205": "探针温度值"
#探针温度值越界:探针温度值
"206": "探针温度值"
#最高电压管理系统号异常:最高电压管理系统号
"207": "最高电压管理系统号"
#最高电压管理系统号无效:最高电压管理系统号
"208": "最高电压管理系统号"
#最高电压管理系统号越界:最高电压管理系统号
"209": "最高电压管理系统号"
#最高电压超级电容单体代号越界:最高电压超级电容单体代号
"210": "最高电压超级电容单体代号"
#超级电容单体电压最高值异常:超级电容单体电压最高值
"211": "超级电容单体电压最高值"
#超级电容单体电压最高值无效:超级电容单体电压最高值
"212": "超级电容单体电压最高值"
#超级电容单体电压最高值越界:超级电容单体电压最高值
"213": "超级电容单体电压最高值"
#最低电压管理系统号异常:最低电压管理系统号
"215": "最低电压管理系统号"
#最低电压管理系统号无效:最低电压管理系统号
"216": "最低电压管理系统号"
#最低电压管理系统号越界:最低电压管理系统号
"217": "最低电压管理系统号"
#最低电压超级电容单体代号越界:最低电压超级电容单体代号
"218": "最低电压超级电容单体代号"
#超级电容单体电压最低值异常:超级电容单体电压最低值
"219": "超级电容单体电压最低值"
#超级电容单体电压最低值无效:超级电容单体电压最低值
"220": "超级电容单体电压最低值"
#超级电容单体电压最低值越界:超级电容单体电压最低值
"221": "超级电容单体电压最低值"
#最高温度管理系统号异常:最高温度管理系统号
"223": "最高温度管理系统号"
#最高温度管理系统号无效:最高温度管理系统号
"224": "最高温度管理系统号"
#最高温度管理系统号越界:最高温度管理系统号
"225": "最高温度管理系统号"
#最高温度探针代号越界:最高温度探针代号
"226": "最高温度探针代号"
#最高温度值异常:最高温度值
"227": "2143"
#最高温度值无效:最高温度值
"228": "2143"
#最高温度值越界:最高温度值
"229": "2143"
#最低温度管理系统号异常:最低温度管理系统号
"231": "最低温度管理系统号"
#最低温度管理系统号无效:最低温度管理系统号
"232": "最低温度管理系统号"
#最低温度管理系统号越界:最低温度管理系统号
"233": "最低温度管理系统号"
#最低温度探针代号越界:最低温度探针代号
"234": "最低温度探针代号"
#最低温度值异常:最低温度值
"235": "2145"
#最低温度值无效:最低温度值
"236": "2145"
#最低温度值越界:最低温度值
"237": "2145"
#未上传整车数据:
"239": "未上传整车数据"
#未上传动力蓄电池最小并联单元电压数据:
"240": "未上传动力蓄电池最小并联单元电压数据"
#未上传动力蓄电池温度数据:
"241": "未上传动力蓄电池温度数据"
#未上传驱动电机数据:
"242": "未上传驱动电机数据"
#未上传燃料电池发动机及车载氢系统数据:
"243": "未上传燃料电池发动机及车载氢系统数据"
#未上传燃料电池电堆数据:
"244": "未上传燃料电池电堆数据"
#未上传发动机数据:
"245": "未上传发动机数据"
#未上传车辆位置数据:
"246": "未上传车辆位置数据"
#未上传超级电容器数据:
"247": "未上传超级电容器数据"
#未上传超级电容器极值数据:
"248": "未上传超级电容器极值数据"
#坐标系异常:坐标系
"251": "坐标系"
#坐标系无效:坐标系
"252": "坐标系"
#坐标系无定义:坐标系
"253": "坐标系"
#未上传报警数据:
"258": "未上传报警数据"
#车辆状态非 1 启动且非 2 熄火:
"259": "车辆状态非1启动且非2熄火"