signal:
  #充电状态
  21AA:
    scale: null
    offset: null
    min: 1
    max: 4
    errorValue: 254
    invalidValue: 255
  #总电流
  215D:
    scale: 10
    offset: 1000
    min: 0
    max: 60000
    errorValue: 65534
    invalidValue: 65535
  #总电压
  215C:
    scale: 10
    offset: null
    min: 0
    max: 60000
    errorValue: 65534
    invalidValue: 65535
  #车辆状态
  220C:
    scale: null
    offset: null
    min: 1
    max: 3
    errorValue: 254
    invalidValue: 155
  #纬度
  207B:
    scale: 1000000
    offset: 90
    min: 0
    max: 90000000
    errorValue: null
    invalidValue: null
  #经度
  207A:
    scale: 1000000
    offset: 180
    min: 0
    max: 180000000
    errorValue: null
    invalidValue: null
  #最低温度值
  2145:
    scale: null
    offset: null
    min: 0
    max: 250
    errorValue: 254
    invalidValue: 255
  #最高报警等级
  220B:
    scale: null
    offset: null
    min: 1
    max: 4
    errorValue: 254
    invalidValue: 255
